const express = require('express');
const { addStudent,deleteStudentById,changeStudentPassword,getRoutine,updateRoutine ,getTeaAvailability,updateTeaAvailability,addNotification,getNotification,deleteNotification,addComplaint,getComplaint,deleteAllComplaint,deleteOneComplaint,getRozastatus,postRozastatus,getStudentinfo,changeStudentRoom,getrozaRoutine,updaterozaRoutine,getPriceroutine,updateMealPrices} = require('../controllers/studentController');
const { loginStudent ,loginAdmin} = require('../controllers/studentLoginController');
const { deleteAllMeals,deleteAllMealsRoza } = require('../controllers/getMealController');
const router = express.Router();
router.post('/add-student', addStudent);
router.post('/login', loginStudent);
router.post('/login-admin',loginAdmin);
router.delete('/students/delete/:id', deleteStudentById);
router.put('/change-student-password', changeStudentPassword); 
router.get('/get-routine', getRoutine);
router.get('/roza-get-routine', getrozaRoutine);
router.put('/update-routine', updateRoutine);
router.put('/roza-update-routine', updaterozaRoutine);
router.post('/add-notifications', addNotification);
router.get('/get-tea-availability', getTeaAvailability);
router.put('/update-tea-availability', updateTeaAvailability);
router.get('/notifications', getNotification);
router.delete('/delete-notifications/:id', deleteNotification);
router.post('/add-complaint', addComplaint);
router.get('/get-complaint', getComplaint);
router.delete('/delete-all-complaint', deleteAllComplaint);
router.delete('/delete-complaint/:id', deleteOneComplaint);
router.post('/add-rozastatus', postRozastatus);
router.get('/get-rozastatus',getRozastatus);
router.delete('/delete-all-meals', deleteAllMeals);
router.delete('/delete-all-meals-roza', deleteAllMealsRoza );
router.get('/student-info',getStudentinfo);
router.put('/change-student-room', changeStudentRoom);
router.get('/get-prices',getPriceroutine);updateMealPrices
router.put('/update-prices', updateMealPrices);
module.exports = router;
